require 'simplecov'
SimpleCov.start
require 'minitest/autorun'
require 'minitest/pride'
require 'pry'
require 'csv'
require 'date'
require './lib/enigma'
require './lib/cipher_maker'
require './lib/key_generator'
require './lib/offset_generator'
